// Builds the hero's inner ring with its Flower of Life texture:
// src/assets/art/hero/ring-inner.svg in, src/assets/art/hero/ring-inner-geometry.svg out.
// The pattern is a grid of equal circles, cut off at an outer circle three circles wide,
// drawn as solid lines (no transparency) and clipped to the ring's wobbly shape.
// Run with `node scripts/flower-of-life.mjs` after changing the settings below.
import { readFileSync, writeFileSync } from 'node:fs';

const DIAMETER = 960; // pattern size in hero design px; bigger than the ring so it fills it edge to edge
const STROKE = 5; // line width in hero design px
const COLOR = '#3a493a'; // 8% cream (#f3e9d2) over the ring's green (#2a3b2d), pre-blended

const src = readFileSync(new URL('../src/assets/art/hero/ring-inner.svg', import.meta.url), 'utf8');
const [, w, h, viewBox] = src.match(/width="([\d.]+)" height="([\d.]+)" viewBox="([^"]+)"/);
const d = src.match(/ d="([^"]+)"/)[1];
const [vx, vy, vw, vh] = viewBox.split(' ').map(Number);
const cx = vx + vw / 2;
const cy = vy + vh / 2;

const R = DIAMETER / 2;
const r = R / 3;
const n = (v) => +v.toFixed(2);
let path = '';
for (let i = -6; i <= 6; i++) {
  for (let j = -6; j <= 6; j++) {
    // Columns run vertically, so a petal points straight up, as on the shop's sign.
    const x = (r * j * Math.sqrt(3)) / 2;
    const y = r * (i + j / 2);
    const dist = Math.hypot(x, y);
    if (dist - r >= R - 1e-6) continue; // entirely outside
    if (dist + r <= R + 1e-6) {
      // entirely inside: a full circle
      path += `M${n(cx + x + r)} ${n(cy + y)}A${n(r)} ${n(r)} 0 1 0 ${n(cx + x - r)} ${n(cy + y)}A${n(r)} ${n(r)} 0 1 0 ${n(cx + x + r)} ${n(cy + y)}`;
      continue;
    }
    // Crosses the outer circle: keep the arc that's inside it.
    const phi = Math.atan2(y, x);
    const a = Math.acos(Math.min(1, Math.max(-1, (R * R - dist * dist - r * r) / (2 * dist * r))));
    const t0 = phi + a;
    const t1 = phi + 2 * Math.PI - a;
    const at = (t) => `${n(cx + x + r * Math.cos(t))} ${n(cy + y + r * Math.sin(t))}`;
    path += `M${at(t0)}A${n(r)} ${n(r)} 0 ${t1 - t0 > Math.PI ? 1 : 0} 1 ${at(t1)}`;
  }
}
path += `M${n(cx + R)} ${n(cy)}A${n(R)} ${n(R)} 0 1 0 ${n(cx - R)} ${n(cy)}A${n(R)} ${n(R)} 0 1 0 ${n(cx + R)} ${n(cy)}`;

const out = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${viewBox}" fill="none"><!-- Generated by scripts/flower-of-life.mjs; edit that, not this. --><defs><clipPath id="ring"><path d="${d}"/></clipPath></defs><path d="${d}" fill="#2A3B2D"/><path d="${path}" stroke="${COLOR}" stroke-width="${STROKE}" clip-path="url(#ring)"/><path d="${d}" stroke="#121210" stroke-width="5"/></svg>
`;
writeFileSync(new URL('../src/assets/art/hero/ring-inner-geometry.svg', import.meta.url), out);
console.log('wrote src/assets/art/hero/ring-inner-geometry.svg');
